// * https://react-styleguidist.js.org/docs/getting-started
// login en nodejs
// todo https://stackoverflow.com/questions/43622127/filtering-table-multiple-columns
POST http://localhost:9000/maintenance/ HTTP/1.1
Content-Type: application/json

{
    "ObservacionesMantenimiento": 1,
    "IdEquipo" : 1,
    "IdTipoMantenimiento": 2
}
###
GET http://localhost:9000/sucursales/all HTTP/1.1


###
PUT  http://localhost:9000/employee/1 HTTP/1.1
Content-Type: application/json

{
    "NombreEmpleado": "Ejemplo 1",
    "Email" : "ejemplo@ejemplo.com",
    "IdSucursal": 1,
    "IdCiudad": 1,
    "IdArea": 1,
    "EstadoEmpleado": 0
}

###
GET http://localhost:9000/category/table HTTP/1.1

###
POST http://localhost:9000/bitacora HTTP/1.1
Content-Type: application/json

{
    "Accion": "RRHH",
    "Modulo": "RRHH",
}

###
put http://localhost:9000/category/update/1 HTTP/1.1
Content-Type: application/json

{
    "CaracteristicaDescripcion": "Marcas",
    "Placeholder": "Marcas",
    "Requerido": 0,
    "IdCaracteristica": 1
}


###

POST http://localhost:9000/auth/register HTTP/1.1
Content-Type: application/json

{
    "NombreUsuario": "crist12",
    "ContraseniaUsuario": "ejemplo"
}

###
POST http://localhost:9000/auth/login HTTP/1.1
Content-Type: application/json

{
    "NombreUsuario": "crist12",
    "ContraseniaUsuario": "ejemplo"
}

###
GET http://localhost:9000/auth/login HTTP/1.1

/*		  SELECT GROUP_CONCAT(IF(b.CaracteristicaTipo = 4, c.OpcionDescripcion, a.Respuesta) SEPARATOR ' ') AS 'Equipo', e.DescripcionEstado, A.IdEquipoIngresado 
		  , F.IdEmpleado, IFNULL(G.NombreEmpleado, "N/A") FROM caracteristicarespuesta AS A 
        INNER JOIN caracteristica AS B ON A.IdCategoria = B.IdCategoria AND A.IdCaracteristica = B.IdCaracteristica 
        LEFT JOIN caracteristicaopcion AS C ON A.Respuesta = C.IdOpcion AND A.IdCategoria = C.IdCategoria AND A.IdCaracteristica = C.IdCaracteristica 
        JOIN equiposestado AS D ON A.IdEquipoIngresado = D.IdEquipo 
        JOIN estados E ON D.TipoEstado = E.IdEstado 
        JOIN asignaciones F ON F.IdEquipo = A.IdEquipoIngresado
        JOIN empleados G ON F.IdEmpleado = G.IdEmpleado
        WHERE A.IdCaracteristica IN(1, 3, 6) AND A.IdCategoria = 1 
        GROUP BY A.FechaIngreso, F.IdEmpleado
