// * https://react-styleguidist.js.org/docs/getting-started
// login en nodejs
// todo https://stackoverflow.com/questions/43622127/filtering-table-multiple-columns
POST http://localhost:9000/control/equi HTTP/1.1
Content-Type: application/json

{
    "IdEquipo": 1,
    "TipoEstado" : 1
}
###
GET http://localhost:9000/assignment/status/7 HTTP/1.1


###
POST http://localhost:9000/control/entries HTTP/1.1
Content-Type: application/json

{
    "IdCategoria": 1,
    "IdCaracteristica" : 1,
    "Respuesta": 2,
    "UsuarioCreo" : "cortiz12"
}

###
GET http://localhost:9000/city/ HTTP/1.1

###
POST http://localhost:9000/area HTTP/1.1
Content-Type: application/json

{
    "DescripcionArea": "RRHH"
}

###
PUT http://localhost:9000/machines/status/7 HTTP/1.1
Content-Type: application/json

{
    "TipoEstado": 3
}

###

POST http://localhost:9000/auth/register HTTP/1.1
Content-Type: application/json

{
    "NombreUsuario": "crist12",
    "ContraseniaUsuario": "ejemplo"
}

###
POST http://localhost:9000/auth/login HTTP/1.1
Content-Type: application/json

{
    "NombreUsuario": "crist12",
    "ContraseniaUsuario": "ejemplo"
}

###
GET http://localhost:9000/auth/login HTTP/1.1