
###
GET http://localhost:9000/sucursales HTTP/1.1

###
POST http://localhost:9000/city/ HTTP/1.1
Content-Type: application/json

{
    "NombreCiudad": "San Nicolás"
}

###
GET http://localhost:9000/city/1 HTTP/1.1

###
POST http://localhost:9000/area HTTP/1.1
Content-Type: application/json

{
    "DescripcionArea": "Marketing"
}

###
PUT http://localhost:9000/area/1 HTTP/1.1
Content-Type: application/json

{
    "DescripcionArea": "MKT"
}

###

POST http://localhost:9000/auth/register HTTP/1.1
Content-Type: application/json

{
    "NombreUsuario": "crist12",
    "ContraseniaUsuario": "ejemplo"
}

###
POST http://localhost:9000/auth/login HTTP/1.1
Content-Type: application/json

{
    "NombreUsuario": "crist12",
    "ContraseniaUsuario": "ejemplo"
}

###
GET http://localhost:9000/auth/login HTTP/1.1